language: node_js
sudo: required
node_js:
- 8.2.1
cache:
  directories:
  - node_modules
notifications: 
email:
  recipients:
  - Vong9262@gmail.com
  on_success: change
  on_failure: always
branches:
  only:
  - hexo
before_install:
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
- chmod +x ./commit-message.sh
install:
- npm install
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo generate
after_script:
- "./commit-message.sh"

env:
  global:
    - secure: bJY//ty5y7GvNBMr7n+XFbrUGTM0kIrnEJPtV3pRZVbhrabw43zVrVO0jl7tjbfcWIU3neyK99kh6T58wdzXnLxeO1vw5k6YDLScQQK6N2l/Q1GTvDIKdACgB8EYcNAYb6zXwsnxY5/nosKx2O9FJWlZCNx3fcnZCnOjYF0qXXYJ8NAbxH7Ct5hAufwQuEVtIK/oCL9oZU3xfbUkw0wKWOyXTJh8YH03BIU0W/E9AS4dBge60qJf6CoqBwgfnZNtrJjjs69zglMSIT8xijPCwhOdFyL7PTdiDEGEe2HfLIwvIDv3IyRFaPsznrD4X3yQYZyRO6nFWpMnBM1tJD2EcI6xkw08fvAl9PPgD/sOWjNckxe2fqEm8cNTVYLcSwtrJcbRh2nEif1+iQ8PZEZUlQZiGntjXpec8ONiC3FVWzIh/yMjNF0R+zeenUoC14st0O+lQnwWN1UHmLhnkH3UVx49wVAmSfrGX894FrHZlbVS+pv9s2dJkk750PvWtgoZvnR+PRFszha+MbVGVqjhh1wSopjF8DE9fnpmhFN4s1TpIS+lCDHYvMyK4diLsknExqcSlrxz1Fpt5p37pWwm5Har33PcjCuFQdHLCC6AGZb8ThhW7CXsmCZMZ/tWhfDO2rJsfFPUtBkGWaDoXFqMMmXiTlOJknRyKBmHq8UEW2s=
    - GH_REF: github.com/wang9262/wang9262.github.io.git
